### ISSUE TITLE
Range check error

### ISSUE THREAD

**Issue by jaclas** [grahamegrieve/delphi-markdown#1]
Try convert string with a lone bracket mark at the beginning of the line:

```
some text
<
other text
```

this raised Range Check exception

**Comment by grahamegrieve** [comment]
I cannot reproduce this?

Grahame

**Comment by jaclas** [comment]
In editor I type:

"uytfuytf

uyguyguyg"

and next I move cursor to empty line (middle line), and type "<". After convert to html I get exception:

![ashampoo_snap_2017 02 06_11h12m56s_001_](https://cloud.githubusercontent.com/assets/17312717/22643219/d7cb873e-ec5d-11e6-8814-dcc05e46e629.png)
![ashampoo_snap_2017 02 06_11h16m35s_002_](https://cloud.githubusercontent.com/assets/17312717/22643223/dbff3f76-ec5d-11e6-93d4-64e1f1220ec7.png)

**Comment by jaclas** [comment]
and?

**Comment by grahamegrieve** [comment]
test case, and  fixed. I think
