### ISSUE TITLE
"@" replaced with "(" in email addresses

### ISSUE THREAD

**Issue by MyLifeOrganized** [grahamegrieve/delphi-markdown#10]
Text:

> \<email@example.com\>

Expected html: mailto:email@example.com
Actual html: mailto:email(example.com

Markdown dialect used: mdDaringFireball

**Comment by mriscoc** [comment]
The output should be an encoded html link:
`<a href="&#x6D;&#97;&#x69;&#x6C;&#x74;&#x6F;:&#101;&#x6D;&#x61;&#x69;&#108;&#64;&#101;&#x78;&#x61;&#109;&#112;&#x6C;&#x65;.&#99;&#111;&#109;">&#x65;&#x6D;&#97;&#x69;&#108;&#x40;&#101;&#120;&#x61;&#109;&#112;&#x6C;&#101;.&#99;&#x6F;&#109;</a>` but it do not stop modern crawlers.

**Comment by grahamegrieve** [comment]
fixed
