### ISSUE TITLE
VCL Tester

### ISSUE THREAD

**Issue by BsNoSi** [grahamegrieve/delphi-markdown#11]
Hey Graham – great job, thank you very very much.

So I can get a quick (and convenient) overview of the capabilities of the converter, I created myself a simple VCL with Delphi Tokyo (should be backwards compatible). *Nothing* in compare to your work but if you want you may add it as a demo. There are no dependencies to any libs etc. and a form transports (in my opition) more impressive the capagilites (and few missing) of the processor.

**For those interested in**: ZIP includes all required *current* files of Grahams project, compiles "out of the box": [Markdown-VCL-Test.zip](https://github.com/grahamegrieve/delphi-markdown/files/4270031/Markdown-VCL-Test.zip)

Copy *output* from "memo2" to a html highlighting editor for better readable result (which is nicely compressed)

**Comment by grahamegrieve** [comment]
thanks. Added to the source in \delphi
