### ISSUE TITLE
Missing reaction on two spaces at end of line

### ISSUE THREAD

**Issue by jaclas** [grahamegrieve/delphi-markdown#2]
https://en.wikipedia.org/wiki/Markdown

cite from wiki:

```
"Two spaces at the end of a line leave a  
line break.

=>

<p>Two spaces at the end of a line leave a<br />
line break.</p>"
```

**Comment by grahamegrieve** [comment]
Added Git Hub test Case 2 - looks fine to me. Why do you think there's a problem?

**Comment by jaclas** [comment]
Yes, really is ok, I made a mistake when trying to use it. Sorry.
