### ISSUE TITLE
Incorrect list convertion

### ISSUE THREAD

**Issue by jaclas** [grahamegrieve/delphi-markdown#3]
Two independent list is coverted to one list:
```
* simple list
* without
* number


1. list
2. with
3. numbered items

=>

<ul>
<li><p>simple list</p>
</li>
<li><p>without</p>
</li>
<li><p>number</p>
</li>
<li><p>list</p>
</li>
<li><p>with</p>
</li>
<li><p>numbered items</p>
</li>
</ul>
```

Visual result:

<ul>
<li><p>simple list</p>
</li>
<li><p>without</p>
</li>
<li><p>number</p>
</li>
<li><p>list</p>
</li>
<li><p>with</p>
</li>
<li><p>numbered items</p>
</li>
</ul>

But expected result is:
```
<ul>
<li><p class="parags">simple list</p>
</li>
<li><p class="parags">without</p>
</li>
<li><p class="parags">number</p>
</li>
</ul>

<ol>
<li><p class="parags">list</p>
</li>
<li><p class="parags">with</p>
</li>
<li><p class="parags">numbered items</p>
</li>
</ol>
```

Visual result:
<ul>
<li><p class="parags">simple list</p>
</li>
<li><p class="parags">without</p>
</li>
<li><p class="parags">number</p>
</li>
</ul>

<ol>
<li><p class="parags">list</p>
</li>
<li><p class="parags">with</p>
</li>
<li><p class="parags">numbered items</p>
</li>
</ol>

**Comment by grahamegrieve** [comment]
Added test case, and fixed

**Comment by jaclas** [comment]
Try this:

```
* raz
* dwa
* trzy
1. razz
2. dwaa
3. trzyy

```
...without empty line.

I get:

```
<ul>
<li>raz</li>
<li>dwa</li>
<li>trzy</li>
<li>razz</li>
<li>dwaa</li>
<li>trzyy</li>
</ul>

```

**Comment by jaclas** [comment]
Do you see comments in closed issue?

**Comment by grahamegrieve** [comment]
apparently, but the first came in with a big batch of other stuff and I missed it. Do you want to submit a test case for this (see resources/df)

**Comment by jaclas** [comment]
[test.zip](https://github.com/grahamegrieve/delphi-markdown/files/1333425/test.zip)

In zip I add file txt and bad conversion to html
