### ISSUE TITLE
Infinite loop and out of memory error

### ISSUE THREAD

**Issue by MyLifeOrganized** [grahamegrieve/delphi-markdown#4]
1. Create DaringFireball dialect:
TMarkdownProcessor.createDialect(mdDaringFireball)

2. Add string:

`<file:c:\users>`
or even shorter:
`<\u`

3. Process mardown. 

Result: infinite loop in this place:
class function TUtils.readUntil(out_: TStringBuilder; s: String; start: integer; cend: TSysCharSet): integer;
...
position := escape(out_, s[1 + position + 1], position)  //<--- always returned the same position

**Comment by MyLifeOrganized** [comment]
Possible fix:
in procedure:
class function TUtils.escape(out_: TStringBuilder; ch: char; position: integer): integer;

replace 

  begin
    out_.append('\');
    result := position;
  end;

to

  begin
    out_.append('\');
    result := position+1;
  end;

It fixes the current issue. But I am not sure for the other cases.

**Comment by MyLifeOrganized** [comment]
When do you think you could look into it?

Thanks! 
Andrey.

p.s. And thank you for the great component!

**Comment by MyLifeOrganized** [comment]
Just tested my fix and it broke the images:
This line will not show existing icon with my fix applied.:
`![Image](C:\images\installer.ico)`


So need to find other solution.

**Comment by grahamegrieve** [comment]
fixed and added test case
