### ISSUE TITLE
Space in local links breaks mardown parsing

### ISSUE THREAD

**Issue by MyLifeOrganized** [grahamegrieve/delphi-markdown#6]
Is it possible to use url with spaces for images and links?
I need to replace " " to %20 for the URL to work. 

Example: 
```
Does not show icon due to space in ulr:
![Icon](C:\Google Drive\app-icon-120.png)


Shows the icon normally after replacing  " " to %20:
---
![Icon](C:\Google%20Drive\app-icon-120.png)

```

Is it possible to allow markdown parser to understand spaces in url?
Or maybe there could be some kind of a callback function which will allow to replace space in urls dynamically on the fly?

**Comment by grahamegrieve** [comment]
what's the situation of this with regard to the base specification?

**Comment by MyLifeOrganized** [comment]
It looks like nothing about the spaces in urls in the spec  :(  :
https://daringfireball.net/projects/markdown/syntax#link

**Comment by grahamegrieve** [comment]
ok so, no, this isn't possible. The way links work is that the first space delimits the URL and the title. it has to be that way, and you have to use %20 in the URL. I didn't read it well enough the first time around
